import { headers } from "next/headers";

import CheckInButton from "@/features/booking/components/check-in-button";
import { checkInUrl, formatAccessCode } from "@/features/booking/lib/access-code";
import { checkInMethod } from "@/features/booking/lib/check-in-methods";
import { accessQrSvg } from "@/features/booking/lib/qr";
import { formatFullDate } from "@/features/booking/lib/dates";
import type { GuestBooking } from "@/features/booking/types";

/**
 * How the guest gets through the door — a Server Component so the QR inlines as SVG (no encoder, no
 * image request). ⚠️ **Both methods always show**: one `access_code` opens both doors, so the choice
 * only sets emphasis. Renders nothing once no door is left to open, or for seeded rows without codes.
 *
 * @param booking The guest's own reservation, already scoped by RLS.
 */
export default async function ArrivalInstructions({
    booking,
}: {
    booking: GuestBooking;
}) {
    const { accessCode, checkInMethod: methodId } = booking;

    if (!accessCode || !methodId) return null;
    if (booking.status !== "confirmed" && booking.status !== "checked_in") {
        return null;
    }

    const method = checkInMethod(methodId);

    // Absolute, because a QR is read by a camera app with no origin to resolve a relative
    // path against. Derived from the request rather than an environment variable so it
    // follows the deployment — same approach as the OAuth redirect in features/auth.
    const headerList = await headers();
    const origin = `${headerList.get("x-forwarded-proto") ?? "http"}://${headerList.get("host")}`;
    const qrSvg = await accessQrSvg(checkInUrl(origin, accessCode));

    const isSmartLock = methodId === "smart-lock";

    return (
        <section
            aria-labelledby="arrival-heading"
            className="mt-8 rounded-3xl border border-black/10 p-8"
        >
            <div className="flex flex-wrap items-baseline justify-between gap-4">
                <h2
                    id="arrival-heading"
                    className="text-[20px] font-semibold text-black"
                >
                    Getting in
                </h2>
                <span className="text-[16px] font-medium text-black/60">
                    {method.label}
                </span>
            </div>

            <p className="mt-4 max-w-160 text-[16px] font-medium text-black/60">
                {method.instruction}
            </p>

            <div className="mt-8 flex flex-wrap items-start gap-10">
                {/* Inlined SVG. `dangerouslySetInnerHTML` is unavoidable for an SVG string
                    and safe here: the markup is generated by the qrcode library from a URL
                    this component built, with no guest input anywhere in it. */}
                <div
                    role="img"
                    aria-label={`QR code for the smart door. It contains your access code, ${formatAccessCode(accessCode)}.`}
                    className="w-45 shrink-0 [&>svg]:block [&>svg]:w-full"
                    dangerouslySetInnerHTML={{ __html: qrSvg }}
                />

                <div className="min-w-0">
                    <p className="text-[14px] font-semibold tracking-wide text-black/40 uppercase">
                        Access code
                    </p>
                    {/* tabular-nums so the two groups line up, and a wide tracking because
                        this gets read off a screen and typed into a keypad in the dark. */}
                    <p className="mt-2 font-mono text-[32px] font-semibold tracking-[0.15em] text-black tabular-nums">
                        {formatAccessCode(accessCode)}
                    </p>

                    <p className="mt-4 max-w-100 text-[16px] font-medium text-black/60">
                        {isSmartLock
                            ? "If the reader does not respond — no power, no signal, a flat phone — type these same characters into the lock box beside the door."
                            : "You can also scan the code above at the smart door, if you would rather not use the keypad."}
                    </p>

                    <p className="mt-4 max-w-100 text-[16px] font-medium text-black/60">
                        Valid from {formatFullDate(booking.checkIn)} until you
                        leave on {formatFullDate(booking.checkOut)}.
                    </p>
                </div>
            </div>

            {/* Only while a check-in remains. Shown even before arrival day: `check_in_booking()`
                refusing with the dates beats a mysteriously absent button. */}
            {booking.status === "confirmed" && booking.paidAt && (
                <div className="mt-8 border-t border-black/10 pt-8">
                    <p className="mb-4 max-w-160 text-[16px] font-medium text-black/60">
                        Scanning the code does this too — this button is here for
                        when you are already looking at the screen.
                    </p>
                    <CheckInButton code={accessCode} label="I've arrived" />
                </div>
            )}
        </section>
    );
}
