-- 0012_booking_arrival_and_payment.sql
-- How a guest gets through the door, and what the payment record finally says.
--
-- Run after 0011_booking_writes.sql. Idempotent: safe to re-run.
--
-- ---------------------------------------------------------------------------
-- What this migration is answering
-- ---------------------------------------------------------------------------
-- Until now a booking recorded that someone had paid for some nights, and then
-- said nothing at all about arriving. There were no keys, no codes and no
-- instructions anywhere in the product. Two arrival methods now exist, chosen
-- by the guest BEFORE the booking is made, because "how do I get in" is
-- information you want before you pay, not after:
--
--   'smart-lock'  the code is scanned at the door. Nobody has to be met, which
--                 is the point for a guest who booked a private villa to be
--                 private in.
--   'lock-box'    the same code, typed on a mechanical keypad. It is the backup
--                 that keeps working when the wifi is down, the phone is flat,
--                 or the guest lands with no roaming data.
--
-- ---------------------------------------------------------------------------
-- One credential, two doors
-- ---------------------------------------------------------------------------
-- There is deliberately NO second column for the lock box. `access_code` is the
-- credential; `check_in_method` only decides how it is delivered — rendered as
-- a QR at the smart door, or as digits for the keypad. Two secrets for one lock
-- would be two things to rotate, two things to leak and two things to keep in
-- sync, in exchange for nothing a guest can perceive.
--
-- It follows that `check_in_method` is a preference, not an authorisation: a
-- guest who picked the lock box can still scan, and one whose phone died can
-- still type. That is the whole reason the backup exists.

-- ---------------------------------------------------------------------------
-- 1. Columns
-- ---------------------------------------------------------------------------
-- All four are NULLABLE, and that is not laziness. 140 seeded rows predate
-- every one of these facts; back-filling them would mean inventing a payment
-- method for a payment that never happened and a door code for a door nobody
-- opened. NULL here reads correctly: "this booking was made before the product
-- recorded that".
alter table public.bookings
    add column if not exists check_in_method   text,
    add column if not exists access_code       text,
    add column if not exists payment_method    text,
    add column if not exists payment_reference text;

comment on column public.bookings.check_in_method is
    'How the guest chose to be let in: smart-lock or lock-box. A preference, not an authorisation — the access code works for both.';
comment on column public.bookings.access_code is
    'The door credential. 8 uppercase hex characters, unique across all bookings. Generated by create_booking(), never by the application.';
comment on column public.bookings.payment_method is
    'Which method the guest paid with. Values match the ids in features/booking/lib/payment-methods.ts exactly.';
comment on column public.bookings.payment_reference is
    'The provider''s receipt id. NULL exactly when paid_at is NULL — see bookings_reference_matches_payment.';

-- Kebab-case, matching the slug vocabulary every other table here uses
-- (stays.slug, amenities.slug). A CHECK rather than a lookup table because
-- these are not content: nobody administers them, they have no editable label,
-- and the copy that describes each one is presentation and lives in the app.
alter table public.bookings drop constraint if exists bookings_check_in_method_known;
alter table public.bookings add constraint bookings_check_in_method_known
    check (check_in_method is null or check_in_method in ('smart-lock', 'lock-box'));

-- ⚠️ These three strings are also the `PaymentMethodId` union in
-- features/booking/lib/payment-methods.ts. One vocabulary, no translation
-- layer, no mapping function to forget to update.
alter table public.bookings drop constraint if exists bookings_payment_method_known;
alter table public.bookings add constraint bookings_payment_method_known
    check (payment_method is null or payment_method in ('gopay', 'bank-transfer', 'card'));

-- A reference is a receipt, so there cannot be one for a payment that never
-- completed. Same spirit as bookings_discount_ok: the pair is checkable, so
-- check it rather than trusting two call sites to agree.
--
-- ⚠️ Only ONE direction is a constraint, and the missing half is worth writing
-- down because it looks like an omission. The obvious rule would be
-- `(paid_at is null) = (payment_reference is null)` — a paid booking must have
-- a receipt. The 140 seeded rows make that unenforceable: seed/0004 stamps
-- paid_at on rows where, in its own words, "no money changed hands, nobody
-- stayed anywhere". They are paid with nothing behind them, and back-filling
-- invented receipts to satisfy a constraint would be putting fiction in a
-- financial record to make a rule look tidy.
--
-- The half that IS enforceable covers the direction that could actually go
-- wrong in code. The other half is guaranteed by settle_booking_payment(),
-- which refuses to stamp paid_at without a reference (SB014).
alter table public.bookings drop constraint if exists bookings_reference_matches_payment;
alter table public.bookings add constraint bookings_reference_matches_payment
    check (payment_reference is null or paid_at is not null);

-- The code is looked up BY ITSELF at the door (see get_check_in_invite), so it
-- has to be unique — and the unique index is also what makes that lookup an
-- index scan instead of a sequential one over every booking ever made.
create unique index if not exists bookings_access_code_key
    on public.bookings (access_code)
    where access_code is not null;

-- ---------------------------------------------------------------------------
-- 2. A fifth status: 'no_show'
-- ---------------------------------------------------------------------------
-- 0009 fixed four values and explained why 'unconfirmed' was dropped. This adds
-- one that is genuinely missing rather than redundant: a guest who paid, whose
-- stay has ended, and who never arrived.
--
-- The alternative was to let the lifecycle job in 0013 call that 'checked_out'.
-- That is a lie the guest can read on their own trips page, and it would also
-- destroy the one number this column exists to make answerable — how many
-- bookings actually turned into stays.
--
-- Widening a CHECK is safe on existing rows; nothing currently holds the value.
alter table public.bookings drop constraint if exists bookings_status_known;
alter table public.bookings add constraint bookings_status_known
    check (status in ('confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show'));

-- ---------------------------------------------------------------------------
-- 3. create_booking — now records the method and mints the code
-- ---------------------------------------------------------------------------
-- The signature changed, so the old one has to go: Postgres would otherwise
-- keep both and PostgREST would have to guess between two overloads.
drop function if exists public.create_booking(text, date, date, smallint, text);

-- Two new SQLSTATEs join the set declared in 0011 §4:
--   SB008  unknown payment method
--   SB009  unknown arrival method
--
-- Both are also CHECK constraints above. Raised here as well because a
-- constraint violation arrives as 23514 with a constraint name attached, which
-- tells the application which rule broke but not which field the guest should
-- look at — and these are the only two values it could act on.
create or replace function public.create_booking(
    p_slug            text,
    p_start           date,
    p_end             date,
    p_num_guests      smallint,
    p_guest_notes     text default null,
    p_payment_method  text default null,
    p_check_in_method text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_guest_id   uuid   := auth.uid();
    v_stay       record;
    -- The villa's local day, not the server's. On Vercel the server clock is
    -- UTC, and a guest in Jakarta booking at 07:00 on the 3rd would be told the
    -- 3rd is in the past. Bali is WITA (UTC+8); Asia/Makassar is its zone.
    v_today      date   := (now() at time zone 'Asia/Makassar')::date;
    v_code       text;
    v_attempt    int    := 0;
    v_booking_id bigint;
begin
    if v_guest_id is null then
        raise exception 'A booking must be made by a signed-in guest'
            using errcode = 'SB003';
    end if;

    -- The FK on guest_id would catch a missing row anyway, but as a foreign key
    -- violation nobody can act on. This is the "trigger never fired" case that
    -- app/(auth)/account/page.tsx also has copy for.
    if not exists (select 1 from public.guests g where g.id = v_guest_id) then
        raise exception 'No guest profile exists for this account'
            using errcode = 'SB005';
    end if;

    if p_payment_method is null
       or p_payment_method not in ('gopay', 'bank-transfer', 'card') then
        raise exception 'Unknown payment method %', coalesce(p_payment_method, '(none)')
            using errcode = 'SB008';
    end if;

    if p_check_in_method is null
       or p_check_in_method not in ('smart-lock', 'lock-box') then
        raise exception 'Unknown arrival method %', coalesce(p_check_in_method, '(none)')
            using errcode = 'SB009';
    end if;

    -- The price snapshot's source, and the capacity check's, in one lookup.
    select s.id, s.price_per_night, s.discount, s.capacity
    into v_stay
    from public.stays s
    where s.slug = p_slug;

    if not found then
        raise exception 'No stay with slug %', p_slug using errcode = 'SB004';
    end if;

    if p_start < v_today then
        raise exception 'Check-in % is in the past', p_start
            using errcode = 'SB002';
    end if;

    if p_num_guests > v_stay.capacity then
        raise exception '% guests exceeds the villa capacity of %',
            p_num_guests, v_stay.capacity
            using errcode = 'SB001';
    end if;

    -- The door code. Eight hex characters — 4.3 billion values, and hex has no
    -- O/0 or I/1 pair to misread off a keypad in the dark. gen_random_uuid() is
    -- in pg_catalog on PG13+, so it needs no extension and survives the empty
    -- search_path above.
    --
    -- The loop exists because the unique index is real: a collision must cost a
    -- retry, not a failed booking. Five attempts against 2^32 values is
    -- generous to the point of being decorative, which is the intended margin.
    loop
        v_attempt := v_attempt + 1;
        v_code := upper(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 8));

        exit when not exists (
            select 1 from public.bookings b where b.access_code = v_code
        );

        if v_attempt >= 5 then
            raise exception 'Could not generate a unique access code after % attempts',
                v_attempt using errcode = 'SB013';
        end if;
    end loop;

    -- Everything else is already a table constraint: end_date > start_date,
    -- num_guests > 0, and the discount bounds. Re-checking them here would be a
    -- second copy of a rule that is already enforced, which is how two copies
    -- start disagreeing.
    insert into public.bookings (
        stay_id, guest_id, start_date, end_date, num_guests,
        unit_price_per_night, discount_per_night, status, guest_notes,
        payment_method, check_in_method, access_code
    )
    values (
        v_stay.id, v_guest_id, p_start, p_end, p_num_guests,
        v_stay.price_per_night, v_stay.discount,
        -- 'confirmed' with paid_at still NULL: the row exists, so the exclusion
        -- constraint is already holding these dates against anyone else, but
        -- nothing has been charged yet. settle_booking_payment() closes it.
        'confirmed',
        nullif(btrim(coalesce(p_guest_notes, '')), ''),
        p_payment_method, p_check_in_method, v_code
    )
    returning id into v_booking_id;

    return v_booking_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. settle_booking_payment — now keeps the receipt
-- ---------------------------------------------------------------------------
drop function if exists public.settle_booking_payment(bigint, boolean);

create or replace function public.settle_booking_payment(
    p_booking_id bigint,
    p_paid       boolean,
    p_reference  text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_guest_id uuid := auth.uid();
    v_status   text;
    v_paid_at  timestamptz;
begin
    select b.status, b.paid_at
    into v_status, v_paid_at
    from public.bookings b
    where b.id = p_booking_id
      -- Ownership is the WHERE clause, not a separate check: a booking that is
      -- not the caller's is indistinguishable from one that does not exist,
      -- which is also what stops this becoming a way to probe for booking ids.
      and b.guest_id = v_guest_id;

    if not found then
        raise exception 'No booking % for this guest', p_booking_id
            using errcode = 'SB006';
    end if;

    if v_paid_at is not null or v_status <> 'confirmed' then
        raise exception 'Booking % has already been settled', p_booking_id
            using errcode = 'SB007';
    end if;

    if p_paid then
        -- This is the half of the paid/receipt pair that could not be a CHECK
        -- (see bookings_reference_matches_payment). Enforced here instead, in
        -- the one function that can ever set paid_at.
        if nullif(btrim(coalesce(p_reference, '')), '') is null then
            raise exception 'A settled payment must carry a reference'
                using errcode = 'SB014';
        end if;

        update public.bookings
        set paid_at = now(), payment_reference = btrim(p_reference)
        where id = p_booking_id;
    else
        -- paid_at deliberately stays NULL, and so does the reference. 0009:
        -- "NULL means unpaid, and stays NULL on a cancellation that was never
        -- charged." A declined attempt produced no receipt to keep.
        update public.bookings set status = 'cancelled' where id = p_booking_id;
    end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. The door: get_check_in_invite and check_in_booking
-- ---------------------------------------------------------------------------
-- ⚠️ Both are granted to `anon`, and that is the design rather than an
-- oversight.
--
-- A door code is a door code. The partner who arrives on an earlier flight, the
-- guest whose session expired on the plane, the friend collecting the keys —
-- all of them have the code and none of them can be asked to log in on a
-- doorstep at midnight. Requiring a session here would reintroduce exactly the
-- friction self check-in exists to remove.
--
-- What that costs is bounded by construction, and both halves are worth stating:
--
--   * get_check_in_invite's RETURN TYPE is the allow-list, the same doctrine as
--     get_stay_booked_ranges in 0010. Villa name, location, the two dates, and
--     whether check-in already happened. No price, no guest, no notes, no id.
--   * check_in_booking can perform exactly one transition, on exactly one row,
--     and returns nothing. Somebody holding a stranger's code can mark that
--     stay as begun. They cannot read it, move it, cancel it or pay for it.
--
-- The code is 4.3 billion values wide and is never listed anywhere, so guessing
-- one is not a route in either.

create or replace function public.get_check_in_invite(p_code text)
returns table (
    stay_name          text,
    stay_location      text,
    start_date         date,
    end_date           date,
    already_checked_in boolean
)
language sql
stable
security definer
set search_path = ''
as $$
    select s.name, s.location, b.start_date, b.end_date, (b.status = 'checked_in')
    from public.bookings b
    join public.stays s on s.id = b.stay_id
    where b.access_code = upper(btrim(p_code))
      -- A cancelled or no-show booking has no door to open, and a completed one
      -- is over. Returning nothing makes all of them a 404, which is also the
      -- right answer for a code that never existed.
      and b.status in ('confirmed', 'checked_in');
$$;

-- Moves 'confirmed' -> 'checked_in'. Returns the booking id so the caller can
-- link a signed-in guest straight to their reservation.
--
--   SB010  no such code, or the booking is not in a state that can be entered
--   SB011  not paid for
--   SB012  today is outside the stay
create or replace function public.check_in_booking(p_code text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_today   date := (now() at time zone 'Asia/Makassar')::date;
    v_booking record;
begin
    select b.id, b.status, b.paid_at, b.start_date, b.end_date
    into v_booking
    from public.bookings b
    where b.access_code = upper(btrim(p_code))
      and b.status in ('confirmed', 'checked_in');

    if not found then
        raise exception 'No booking can be entered with that code'
            using errcode = 'SB010';
    end if;

    -- Scanning twice is not a mistake anybody made. The guest is already
    -- inside; saying "you are checked in" a second time is the honest answer,
    -- and an error here would send them looking for a problem that is not there.
    if v_booking.status = 'checked_in' then
        return v_booking.id;
    end if;

    if v_booking.paid_at is null then
        raise exception 'Booking % has not been paid for', v_booking.id
            using errcode = 'SB011';
    end if;

    -- `< end_date`, not `<=`: end_date is the departure day and the guest is
    -- out by 11:00 AM. Arriving on it is not arriving at all — 0009's exclusive
    -- end date, enforced one more time at the door.
    if v_today < v_booking.start_date or v_today >= v_booking.end_date then
        raise exception 'Booking % cannot be entered today', v_booking.id
            using errcode = 'SB012';
    end if;

    update public.bookings
    set status = 'checked_in'
    where id = v_booking.id;

    return v_booking.id;
end;
$$;

-- EXECUTE is granted to PUBLIC by default on a new function, which on a
-- SECURITY DEFINER function is the whole hazard. Revoke first, then hand it
-- back deliberately.
revoke all on function public.create_booking(text, date, date, smallint, text, text, text) from public;
revoke all on function public.settle_booking_payment(bigint, boolean, text)                from public;
revoke all on function public.get_check_in_invite(text)                                    from public;
revoke all on function public.check_in_booking(text)                                       from public;

grant execute on function public.create_booking(text, date, date, smallint, text, text, text) to authenticated;
grant execute on function public.settle_booking_payment(bigint, boolean, text)                to authenticated;

-- The two that `anon` may call. See the note above §5.
grant execute on function public.get_check_in_invite(text) to anon, authenticated;
grant execute on function public.check_in_booking(text)    to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------

-- The five statuses, and the new constraints. Expect the widened status list
-- and three new CHECKs.
select conname, pg_get_constraintdef(oid) as definition
from pg_constraint
where conrelid = 'public.bookings'::regclass
  and conname in ('bookings_status_known', 'bookings_check_in_method_known',
                  'bookings_payment_method_known', 'bookings_reference_matches_payment')
order by conname;

-- Every function here must be SECURITY DEFINER with an empty search_path.
-- Expect prosecdef = true and proconfig = {search_path=} on all four.
select proname, prosecdef, proconfig
from pg_proc
where pronamespace = 'public'::regnamespace
  and proname in ('create_booking', 'settle_booking_payment',
                  'get_check_in_invite', 'check_in_booking')
order by proname;

-- Exactly one signature each — a leftover overload would make PostgREST pick
-- between them at random. Expect 1 row per name.
select proname, count(*) as signatures
from pg_proc
where pronamespace = 'public'::regnamespace
  and proname in ('create_booking', 'settle_booking_payment')
group by proname;

-- The seeded rows keep their NULLs; only bookings made through the app carry
-- the new facts. Expect 140 rows with everything null, until you book one.
select count(*) filter (where access_code is null)     as no_code,
       count(*) filter (where access_code is not null) as with_code,
       count(*) filter (where payment_method is null)  as no_method
from public.bookings;

-- The allow-list, proven. Run with the role switched to `anon`: this must
-- return exactly five columns and no others, and the table itself must still
-- return 0 rows.
--     select * from public.get_check_in_invite('A3F72C9B');
--     select count(*) from public.bookings;              -- expect 0 rows
